version: "3"
services:
  message-dashboard:
    build:
      context: .
    image: registry.wacodis.demo.52north.org/message-dashboard:1.0.2-SNAPSHOT
    network_mode: "host"
    ports:
      - 8080:8080
    environment:
      - spring.rabbitmq.host=wacodis.demo.52north.org
      - spring.rabbitmq.password=wacojo2018
