version: "3"
services:
  message-dashboard:
    build:
      context: .
    image: wacodis/message-dashboard:1.0.2
    ports:
      - 8080:80
    environment:
      - spring.rabbitmq.host=localhost
      - spring.rabbitmq.password=password
      - spring.rabbitmq.username=user
      - PORT=80
