version: "3"
services:
  message-dashboard:
    build:
      context: .
    image: wacodis/message-dashboard:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_RABBITMQ_HOST=host.docker.internal
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=rabbitmq
      - SPRING_RABBITMQ_PASSWORD=rabbitmq