server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    config:
      url: http://localhost:8888
    stream:
      bindings:
        jobs-new:
          destination: wacodis.prod.jobs.new
          binder: wacodis_rabbit
          group: messageConsumers
        jobs-status:
          destination: wacodis.prod.jobs.status
          binder: wacodis_rabbit
          group: messageConsumers
        jobs-deletion:
          destination: wacodis.prod.jobs.deleted
          binder: wacodis_rabbit
          group: messageConsumers
        tools-execute:
          destination: wacodis.prod.tools.execute
          binder: wacodis_rabbit
          group: messageConsumers
        tools-finished:
          destination: wacodis.prod.tools.finished
          binder: wacodis_rabbit
          group: messageConsumers
        data-available:
          destination: wacodis.prod.data.available
          binder: wacodis_rabbit
          group: messageConsumers
        data-accessible:
          destination: wacodis.prod.data.accessible
          binder: wacodis_rabbit
          group: messageConsumers
      binders:
        wacodis_rabbit:
          type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
