server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    config:
      url: http://localhost:8888
    stream:
      bindings:
        jobs-new:
          destination: wacodis.test.jobs.new
          binder: wacodis_rabbit
          group: dashboardConsumers
        jobs-status:
          destination: wacodis.test.jobs.status
          binder: wacodis_rabbit
          group: dashboardConsumers
        jobs-deletion:
          destination: wacodis.test.jobs.deleted
          binder: wacodis_rabbit
          group: dashboardConsumers
        tools-execute:
          destination: wacodis.test.tools.execute
          binder: wacodis_rabbit
          group: dashboardConsumers
        tools-finished:
          destination: wacodis.test.tools.finished
          binder: wacodis_rabbit
          group: dashboardConsumers
        tools-failure:
          destination: wacodis.test.tools.failure
          binder: wacodis_rabbit
          group: dashboardConsumers
        data-available:
          destination: wacodis.test.data.available
          binder: wacodis_rabbit
          group: dashboardConsumers
        data-accessible:
          destination: wacodis.test.data.accessible
          binder: wacodis_rabbit
          group: dashboardConsumers
      binders:
        wacodis_rabbit:
          type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
